export const DOTS = {
    ADD_DOT : 'ADD_DOT',
    ADD_MULTIPLE_DOTS : 'ADD_MULTIPLE_DOTS',
    REMOVE_DOT : 'REMOVE_DOT',
    REMOVE_MULTIPLE_DOTS : 'REMOVE_MULTIPLE_DOTS',
    REZONE_DOT : 'REZONE_DOT',

    BASE_CHANGED: 'BASE_CHANGED',
    STABILIZE : 'STABILIZE',
    ONE_STEP_STABILIZE : 'ONE_STEP_STABILIZE',
    CLEAR : 'CLEAR',
    DISPLAY : 'DISPLAY',
    ADDITION : 'ADDITION',
    SUBTRACT : 'SUBTRACT',
    MULTIPLY : 'MULTIPLY',
    DIVIDE : 'DIVIDE'
};