export enum ACTIONS {
  ADD_DOT = 'ADD_DOT',
  ADD_MULTIPLE_DOTS = 'ADD_MULTIPLE_DOTS',
  REMOVE_DOT = 'REMOVE_DOT',
  REMOVE_MULTIPLE_DOTS = 'REMOVE_MULTIPLE_DOTS',
  REZONE_DOT = 'REZONE_DOT',
  SET_DIVISION_RESULT = 'SET_DIVISION_RESULT',

  BASE_CHANGED = 'BASE_CHANGED',
  STABILIZE = 'STABILIZE',
  SHOW_HIDE_PLACE_VALUE = 'SHOW_HIDE_PLACE_VALUE',
  ACTIVATE_MAGIC_WAND = 'ACTIVATE_MAGIC_WAND',
  RESET = 'RESET',

  OPERAND_CHANGED = 'OPERAND_CHANGED',
  OPERATOR_CHANGED = 'OPERATOR_CHANGED',

  START_ACTIVITY = 'START_ACTIVITY',
  START_ACTIVITY_DONE = 'START_ACTIVITY_DONE',

  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
  /*USER_MESSAGE = 'USER_MESSAGE',
  RESET_USER_MESSAGE = 'RESET_USER_MESSAGE',*/
}
