export const ACTIONS = {
    ADD_DOT : 'ADD_DOT',
    ADD_MULTIPLE_DOTS : 'ADD_MULTIPLE_DOTS',
    REMOVE_DOT : 'REMOVE_DOT',
    REMOVE_MULTIPLE_DOTS : 'REMOVE_MULTIPLE_DOTS',
    REZONE_DOT : 'REZONE_DOT',

    BASE_CHANGED: 'BASE_CHANGED',
    STABILIZE : 'STABILIZE',
    SHOW_HIDE_PLACE_VALUE : 'SHOW_HIDE_PLACE_VALUE',
    ACTIVATE_MAGIC_WAND : 'ACTIVATE_MAGIC_WAND',
    RESET : 'RESET',

    OPERAND_CHANGED: 'OPERAND_CHANGED',
};
